### ISSUE TITLE
Travis build indicates hidden failures?

### ISSUE THREAD

**Issue by olegabr** [ChessCom/Chess-Game#13]
For example, here (https://travis-ci.org/ChessCom/Chess-Game/jobs/13015161) we can see:

```
$ bin/phpunit
PHPUnit 3.7.28-1-g598a467 by Sebastian Bergmann.
Configuration read from /home/travis/build/ChessCom/Chess-Game/phpunit.xml.dist
................................................................. 65 / 83 ( 78%)
..................
Time: 760 ms, Memory: 10.50Mb
The command "bin/phpunit" exited with 0.
Done. Your build exited with 0.
```

What does this `65 / 83 ( 78%)` means there? Does it mean that 18 tests are actually failing?

**Comment by cordoval** [comment]
of course not, it is just that at that point in time

**Comment by marcosdsanchez** [comment]
All tests are passing: https://s3.amazonaws.com/archive.travis-ci.org/jobs/13015161/log.txt
